import { dana } from "@/utils/local_font";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import SideBar from "@/components/layouts/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" data-theme="light">
      <body className={`${dana.variable} font-sans`}>
        <div className="grid grid-cols-10 gap-2">
          <div className="col-span-2">
            <SideBar />
          </div>
          <div className="col-span-10 md:col-span-8 h-screen">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
